name: "Sphinx: Render docs"

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v3
      # - name: Build HTML
      #   uses: ammaraskar/sphinx-action@master   
      #   with:
      #       pre-build-command: |
      #         python -m pip install sphinx sphinx_rtd_theme myst_parser m2r
      #         python -m pip install -e .
      # - name: Install dependencies
      #   run: |
      - name: Sphinx build
        run: |
          python -m pip install sphinx sphinx_rtd_theme myst_parser m2r
          python -m pip install -e .
          sphinx-build docs ${{ github.workspace }}/docs/build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: html-docs
          path: ${{ github.workspace }}/docs/build/
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          pre-build-command: |
            pwd
            ls -la
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: docs/build/
