name: "Sphinx: Render docs"

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Sphinx build
        run: |
          python -m pip install sphinx "sphinx_rtd_theme>1" myst_parser m2r renku-sphinx-theme
          python -m pip install -e .
          sphinx-build docs ${{ github.workspace }}/docs/build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: html-docs
          path: ${{ github.workspace }}/docs/build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ${{ github.workspace }}/docs/build
